app/urls.py
from django.urls import path    
from . import views

app_name = "app"

urlpatterns=[
    path('',views.index,name='index'),
    path('projects/',views.projects,name='projects'),
    path('project/<str:pk>/',views.project,name='single-project'),
    path('bible/',views.bible,name='bible'),
    path('videos/',views.videos,name='videos'),
    path('send-email/',views.send_email,name='send_email'),
    path('create-project/',views.createProject,name='create_project'),
]

solascriptura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db.models import Model
import uuid

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True,null=True)
    featured_image = models.ImageField(blank=True,null=True, default='default.jpg')
    verse_text =models.CharField(max_length=200, blank=True,null=True) 
    verse_content =models.TextField( blank=True,null=True) 
    created = models.DateTimeField()
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self):
        return self.title

    

app/views.py
from multiprocessing import context
from django.shortcuts import render, redirect

from django.contrib import messages
from django.db.models import  Q

from .models import Project

# customised email
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import HttpResponse
from solascriptura import settings

from .form import ProjectForm

# Create your views here.
def projects(request):
    search_query = ''
    projects = Project.objects.all()

    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')
        projects = Project.objects.distinct().filter(
        Q(title__icontains=search_query) | 
        Q(author__icontains=search_query) 
    )

    context = {'projects':projects}
    return render(request, 'app/projects.html',context)


def project(request, pk):
    projectObj= Project.objects.get(id=pk)
    context = {'projectObj':projectObj}
    return render(request, 'app/single-project.html',context)



def createProject(request):
    
    form = ProjectForm()

    if request.method == 'POST':
        form  = ProjectForm(request.POST,request.FILES)
        if form.is_valid():
            project = form.save()
            return redirect('projects')
     


    context={'form':form}
    return render(request, 'app/form-template.html', context)

   
def updateProject(request, pk):
    
    if request.method == 'POST':
        form = ProjectForm(request.POST,request.FILES, instance=project)
    if form.is_valid():
        form.save()
        return redirect('projects')
    context={'form':form}
    return render(request, 'projects/project_form.html',context)


def index(request):
    context = {}
    return render(request, 'app/index.html',context)


def bible(request):
    context = {}
    return render(request, 'app/bibleStudies.html',context)

    
def videos(request):
    context = {}
    return render(request, 'app/videos.html',context)

def send_email(request):        
    if request.method == 'POST':
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        body = request.POST.get('body')
        
        html_content = render_to_string('app/email_template.html',{'email': email, 'body':body, 'subject':subject, 'name':name})
        text_content = strip_tags(html_content)

        email = EmailMultiAlternatives(
            subject, # subject
            text_content, #content or body
            settings.EMAIL_HOST, #from email address
            [email],#recepient email list
            # ['ernest6175@gmail.com','elokai6175@gmail.com']  
        )
        email.attach_alternative(html_content,'text/html')
        email.send()
        messages.success(request,'Your mail was successfully sent')
        return redirect('app:projects')
        # return HttpResponse("<h1>Your mail was successfully sent</h1> <br><h1>We will get back to you very soon</h1>")
    return render(request, 'app/single-project.html',context)

templates/app/email_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <style>
        .wrap {
          margin: 5rem auto;
          border: 2px solid black;
          background-color: #eee;
          padding: 1rem;
        }
        .wrap h1 {
          font: size 4rem;
          font-weight: 700;
          color:orangered
        }
        .wrap p {
          font: size 2rem;
          font-weight: 400;
          color:blue
        }
        .pic{
            width: 5rem;
            height: 5rem;
        }
      </style>
  </head>
  <body>
    
      <div class="wrap">
          <!-- <img class="pic"src="https://drive.google.com/file/d/1htHESheDLTSkpp5wNX9IIfO5IYXbE2DS/view?usp=sharing" alt="me"> -->
        <h1>Good morninng {{name}}</h1>
        <p>
          Your subject {{subject}}, is submitted via your email {{email}} to us
        </p>
        <p>
           We will inspect your message <br> {{body}} <br> We will reply you soon
          </p>
      </div>
    </body>
   </div>
</html>

templates/app/form-template.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/icon.svg' %}"
      type="image/x-icon"
    />
    <!-- Icon - IconMonster -->
    <link
      rel="stylesheet"
      href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css"
    />
    <!-- Mumble UI -->
    <link
      rel="stylesheet"
      href=" {% static 'assets/uikit/styles/uikit.css' %}"
    />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'assets/styles/app.css' %}" />

    <title>DevSearch - Connect with Developers!</title>
  </head>

  <body>
    <!-- Header Section -->
    <header class="header">
      <div class="container container--narrow">
        <a href="/" class="header__logo">
          <img src="images/logo.svg" alt="DevSearch Logo" />
        </a>
        <nav class="header__nav">
          <input type="checkbox" id="responsive-menu" />
          <label for="responsive-menu" class="toggle-menu">
            <span>Menu</span>
            <div class="toggle-menu__lines"></div>
          </label>
          <ul class="header__menu">
            <li class="header__menuItem">
              <a href="">Bible Study Lessons</a>
            </li>
            <li class="header__menuItem">
              <a href="">Bible Study Videos</a>
            </li>
            <li class="header__menuItem">
              <a href="">Promises of God</a>
            </li>
            <li class="header__menuItem">
              <a
                href="https://www.amazingfacts.org/bible-study/free-online-bible-school"
                >Amazing facts</a
              >
            </li>
            <li class="header__menuItem">
              <a href="" class="btn btn--sub">Add Project</a>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <!-- Main Section -->
    <!-- CREATE PROJECT ON UI FILE -->
    <main class="formPage my-xl">
      <div class="content-box">
        <div class="formWrapper">
          <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
          <br />

          <form
            class="form"
            method="POST"
            enctype="multipart/form-data"
            action=" "
          >
            {% csrf_token %}
            <!-- Input:Text -->
            {% for field in form%}
            <div class="form__field">
              <label for="formInput#text">{{field.label}} </label>
              {{field}}
            </div>
            {% endfor %}
            <input
              class="btn btn--sub btn--lg my-md"
              type="submit"
              value="Submit"
            />
          </form>
        </div>
      </div>
    </main>
  </body>
</html>

templates/app/projects.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/favicon.ico' %}"
      type="image/x-icon"
    />
    <!-- Icon - IconMonster -->
    <link
      rel="stylesheet"
      href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css"
    />
    <!-- Mumble UI -->
    <link
      rel="stylesheet"
      href="{% static 'assets/uikit/styles/uikit.css' %}"
    />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'assets/styles/app.css' %}" />

    <title>DevSearch - Connect with Developers!</title>
  </head>

  <body>
    <!-- Header Section -->
    <header class="header">
      <div class="container container--narrow">
        <a href="/" class="header__logo">
          <img
            src="{% static 'assets/images/logo.svg' %}"
            alt="DevSearch Logo"
          />
        </a>
        <nav class="header__nav">
          <input type="checkbox" id="responsive-menu" />
          <label for="responsive-menu" class="toggle-menu">
            <span>Menu</span>
            <div class="toggle-menu__lines"></div>
          </label>
          <ul class="header__menu">
            <li class="header__menuItem">
              <a href="">Bible Study Lessons</a>
            </li>
            <li class="header__menuItem">
              <a href="">Bible Study Videos</a>
            </li>
            <li class="header__menuItem">
              <a href="">Promises of God</a>
            </li>
            <li class="header__menuItem">
              <a
                href="https://www.amazingfacts.org/bible-study/free-online-bible-school"
                >Amazing facts</a
              >
            </li>
            <li class="header__menuItem">
              <a href="" class="btn btn--sub">Add Project</a>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <!-- Main Section -->
    <main class="projects">
      <section class="hero-section text-center">
        <div class="container container--narrow">
          <div class="hero-section__box">
            <h2>Search for <span>Bible study</span></h2>
          </div>

          <div class="hero-section__search">
            <form class="form" action="{% url 'app:projects' %}" method="get">
              <div class="form__field">
                <label for="formInput#search">Search By Projects </label>
                <input
                  class="input input--text"
                  id="formInput#search"
                  type="text"
                  name="search_query"
                  placeholder="Search by a keyword"
                />
              </div>

              <input
                class="btn btn--sub btn--lg"
                type="submit"
                value="Search"
              />
            </form>
          </div>
          {%for message in messages %}
          <!--  -->
          <div
            class="alert alert-warning alert-dismissible fade show"
            role="alert"
          >
            <strong>Congratulations!</strong> {{message}}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          <!--  -->
          {% endfor %}
        </div>
      </section>
      <!-- Search Result: DevList -->
      <section class="projectsList">
        <div class="container">
          <div class="grid grid--three">
            {%for project in projects %}
            <div class="column">
              <div class="card project">
                <a
                  href="{% url 'app:single-project' project.id  %} "
                  class="project"
                >
                  <img
                    class="project__thumbnail"
                    src="{% if project.featured_image %}{{project.featured_image.url}}{%else%}{% static 'assets/img/sola.jpg' %}{%endif%}"
                    alt="project thumbnail"
                  />
                  <div class="card__body">
                    <h3 class="project__title">{{project.title}}</h3>
                    <p>
                      by &nbsp;
                      <a
                        class="project__author"
                        href="{% url 'app:single-project' project.id  %}"
                        >{{project.author}}</a
                      >
                    </p>
                    <p class="project--rating">
                      <span style="font-weight: bold">{{project.created}}</span>
                    </p>
                  </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </section>

      <!-- PAGINATION -->
      <div class="pagination">
        <ul class="container">
          <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
          <li><a href="#" class="btn btn--sub">01</a></li>
          <li><a href="#" class="btn">02</a></li>
          <li><a href="#" class="btn">03</a></li>
          <li><a href="#" class="btn">04</a></li>
          <li><a href="#" class="btn">05</a></li>
          <li><a href="#" class="btn">06</a></li>
          <li><a href="#" class="btn">07</a></li>
          <li><a href="#" class="btn">08</a></li>
          <li><a href="#" class="btn">09</a></li>
          <li><a href="#" class="btn">10</a></li>
          <li><a href="#" class="btn">Next &#10095;</a></li>
        </ul>
      </div>
    </main>
  </body>
</html>

templates/app/single-project.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'assets/uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'assets/styles/app.css' %}" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'assets/images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <center>
            <h3 class="singleProject__subtitle">Keys</h3>
            <span class="tag tag--pill  tag--lg">
              <small>Key Text : {{projectObj.verse_text}}</small>
            </span>
          </center>
          <div class="singleProject__toolStack">
            
            <span class="tag  tag--sub tag--lg">
              <p>{{projectObj.verse_content|linebreaksbr}} </p>
            </span>
            
            
          </div>
          
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{% if projectObj.featured_image %}{{projectObj.featured_image.url}}{%else%}{% static 'assets/img/sola.jpg' %}{%endif%}" alt="portfolio thumbnail" />
          <a  class="singleProject__developer">by &nbsp;{{projectObj.author}}</a>
          <h2 class="singleProject__title">{{projectObj.title}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima harum maxime debitis amet voluptates esse
            a perferendis tempora, natus pariatur obcaecati odit quisquam fugit deserunt.

            <br />
            <br />
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic voluptates earum possimus a perferendis culpa
            omnis, libero quae soluta, obcaecati amet. Quam earum ad qui reprehenderit eligendi porro ab possimus
            fugit voluptatem rerum eius sapiente, nemo mollitia aperiam suscipit culpa corrupti officiis dicta soluta
            ut similique! Iste soluta quae tempora alias assumenda? Nam nesciunt nihil enim tempore cum quo
            architecto?
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating comment__author">
              If you have any question or contribution concerning this study, send it to us and we will get back to you via your email
            </h5>

            <form class="form special_form_class" action="{% url 'app:send_email' %}" method="POST" >
              {%csrf_token %}
               <!-- name -->
               <div class="form__field">
                <input
                  class="input input--email"
                  id="name"
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                />
              </div>
              <!-- subject -->
              <div class="form__field">
                <input
                  class="input input--email"
                  id="subject"
                  type="text"
                  name="subject"
                  placeholder="Enter the title of your message"
                />
              </div>
              <!-- email -->
              <div class="form__field">
                <input
                  class="input input--email"
                  id="email"
                  type="email"
                  name="email"
                  placeholder="Enter your email"
                />
              </div>
              <!-- Textarea -->
              <div class="form__field">
                <textarea class="input input--textarea" name="body" id="body"
                  placeholder="Write your comments or question here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Mail Us" />
            </form>
           
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
</body>

</html>